### ISSUE TITLE
Create and test a K8s Job that pushes EFS data to an S3 bucket (Cutover Task)

### ISSUE THREAD

**Issue by escattone** [mdn/infra#107]
# User story
As an MDN staff developer, I want to ensure that we're ready for executing the portion of the cutover plan where we copy the EFS data from MozMEAO to MozIT, so create and test a K8s Job on the MozMEAO cluster (based on `mdn-backup-cron.yaml.j2`) that pushes EFS to the `mdn-shared-backup` S3 bucket.

# Acceptance Criteria
* [x] K8s Job created that pushes EFS data to an S3 bucket
* [x] K8s Job has been successfully tested on the MozMEAO cluster

# Tasks:
* [x] Create K8s Job that pushes EFS data to an S3 bucket
* [x] Create a `Makefile` target that runs the K8s Job
* [x] Test the K8s Job on the MozMEAO cluster

**Comment by escattone** [comment]
See https://github.com/mdn/infra/pull/114

**Comment by escattone** [comment]
I used `make k8s-sync-efs-to-s3-job` to run the job successfully on the MozMEAO cluster on Monday Oct. 8:
```
rjohnson-25186:k8s rjohnson$ kc logs mdn-sync-efs-to-s3-qdvcm
Pushing from /mdn/www/ to s3://mdn-shared-backup/backups/mdn/
Complete
DEADMANSSNITCH_URL is not configured
rjohnson-25186:k8s rjohnson$ kc get job
NAME                               DESIRED   SUCCESSFUL   AGE
mdn-backup-prod-1539043200         1         1            4h
mdn-backup-prod-1539046800         1         1            3h
mdn-backup-prod-1539050400         1         1            2h
mdn-backup-prod-1539054000         1         0            57m
mdn-db-migration                   1         1            4d
mdn-kuma-record-deployment         1         1            4d
mdn-kumascript-record-deployment   1         1            4d
mdn-sync-efs-to-s3                 1         1            6h
rjohnson-25186:k8s rjohnson$ kc get jobs mdn-sync-efs-to-s3 -o yaml
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"name":"mdn-sync-efs-to-s3","namespace":"mdn-prod"},"spec":{"template":{"metadata":{"name":"mdn-sync-efs-to-s3"},"spec":{"containers":[{"env":[{"name":"LOCAL_DIR","value":"/mdn/www/"},{"name":"REMOTE_DIR","value":"/backups/mdn/"},{"name":"BUCKET","value":"s3://mdn-shared-backup"},{"name":"PUSH_OR_PULL","value":"PUSH"},{"name":"AWS_REGION","value":"us-west-2"},{"name":"AWS_S3SYNC_PAGE_SIZE","value":"100"},{"name":"AWS_ACCESS_KEY_ID","valueFrom":{"secretKeyRef":{"key":"access_key","name":"mdn-backup-secrets"}}},{"name":"AWS_SECRET_ACCESS_KEY","valueFrom":{"secretKeyRef":{"key":"secret_key","name":"mdn-backup-secrets"}}}],"image":"mdnwebdocs/mdn-backup:51ae821","imagePullPolicy":"IfNotPresent","name":"mdn-sync-efs-to-s3","volumeMounts":[{"mountPath":"/mdn","name":"mdn-shared"}]}],"restartPolicy":"Never","volumes":[{"name":"mdn-shared","persistentVolumeClaim":{"claimName":"mdn-shared"}}]}}}}
  creationTimestamp: 2018-10-08T22:26:41Z
  labels:
    controller-uid: 3ae0c3a9-cb49-11e8-97d0-0287e8e34e8a
    job-name: mdn-sync-efs-to-s3
  name: mdn-sync-efs-to-s3
  namespace: mdn-prod
  resourceVersion: "108271398"
  selfLink: /apis/batch/v1/namespaces/mdn-prod/jobs/mdn-sync-efs-to-s3
  uid: 3ae0c3a9-cb49-11e8-97d0-0287e8e34e8a
spec:
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 3ae0c3a9-cb49-11e8-97d0-0287e8e34e8a
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 3ae0c3a9-cb49-11e8-97d0-0287e8e34e8a
        job-name: mdn-sync-efs-to-s3
      name: mdn-sync-efs-to-s3
    spec:
      containers:
      - env:
        - name: LOCAL_DIR
          value: /mdn/www/
        - name: REMOTE_DIR
          value: /backups/mdn/
        - name: BUCKET
          value: s3://mdn-shared-backup
        - name: PUSH_OR_PULL
          value: PUSH
        - name: AWS_REGION
          value: us-west-2
        - name: AWS_S3SYNC_PAGE_SIZE
          value: "100"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: access_key
              name: mdn-backup-secrets
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: secret_key
              name: mdn-backup-secrets
        image: mdnwebdocs/mdn-backup:51ae821
        imagePullPolicy: IfNotPresent
        name: mdn-sync-efs-to-s3
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mdn
          name: mdn-shared
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mdn-shared
        persistentVolumeClaim:
          claimName: mdn-shared
status:
  completionTime: 2018-10-09T00:29:36Z
  conditions:
  - lastProbeTime: 2018-10-09T00:29:36Z
    lastTransitionTime: 2018-10-09T00:29:36Z
    status: "True"
    type: Complete
  startTime: 2018-10-08T22:26:41Z
  succeeded: 1
```
