### ISSUE TITLE
Test CDN cutover/rollback on stage (developer.allizom.org)

### ISSUE THREAD

**Issue by escattone** [mdn/infra#112]
# User story
As an MDN staff developer, I want to ensure that we're ready for executing a downtime-free cutover from the MozMEAO CDN's to the MozIT CDN's, so work with AWS to test a cutover from MozMEAO's primary stage CDN to MozIT's primary stage CDN, as well as a rollback.

# Acceptance Criteria
* Downtime-free cutover from MozMEAO's to MozIT's primary stage CDN (`developer.allizom.org`)
* Downtime-free rollback from MozIT's to MozMEAO's primary stage CDN (`developer.allizom.org`)

# Tasks:
* [x] Schedule a date and time for the cutover/rollback with AWS
* [X] Immediately prior to the cutover, run the headless tests against `developer.allizom.org` in a continuous loop
* [x] Add a TXT record for `developer.allizom.org` whose value is the domain name of MozIT's primary stage CDN
* [x] Request that AWS change the `developer.allizom.org` CNAME in CloudFront to point to the MozIT CDN
* [x] Monitor New Relic and Papertrail to ensure there is no downtime
* [x] Request that AWS change the `developer.allizom.org` CNAME in CloudFront to point back to the MozMEAO CDN
* [x] Monitor New Relic to ensure there is no downtime

**Comment by escattone** [comment]
CDN cutover/rollback test scheduled with AWS for Wednesday Oct. 10 at 10am PST. We will test the cutover/rollback for only one CDN, the primary stage CDN (developer.allizom.org).

**Comment by escattone** [comment]
This was completed successfully on Oct. 10, 2018. Painless and flawless.
