### ISSUE TITLE
Post Cutover - AWS & Jenkins Tasks

### ISSUE THREAD

**Issue by escattone** [mdn/infra#130]
# User Story
As an MDN staff developer, after successfully executing the MDN cut-over plan, I'd like to make sure that updates to the MDN repos no longer trigger actions upon MozMEAO-related infrastructure, as well as that any we take care of any AWS tasks (e.g., the sample database downloads are handled from the MozIT AWS account rather than MozMEAO account).

# Acceptance Criteria
* The `mdn-downloads` S3 bucket and its content have been moved from the MozMEAO account to the MozIT account
* The four (4) MDN pipelines within the MozMEAO Jenkins service have been paused/disabled so that we no longer trigger effects within the MozMEAO world (e.g., image pushes to quay.io as well as pushes to MozMEAO Kubernetes clusters)
* Temporary IAM users within the MozIT account that were created solely for the pre-cutover period have been deleted
* Unused S3 buckets have been removed from the MozIT AWS account

# Tasks
* [x] Copy the content of the MozMEAO `mdn-downloads` S3 bucket to a temporary S3 bucket in the MozIT account
* [x] Delete the MozMEAO `mdn-downloads` bucket
* [x] Create a new `mdn-downloads` bucket within the MozIT account (with `public` access)
* [x] Transfer data from temporary S3 bucket to the `mdn-downloads` bucket
* [x] Delete the temporary S3 bucket
* [x] Pause/disable the `mdn_multibranch_pipeline` (Kuma) within the MozMEAO Jenkins service 
* [x] Pause/disable the `kumascript_multibranch_pipeline` (Kumascript) within the MozMEAO Jenkins service
* [x] Pause/disable the `mdn_interactive_examples` pipeline within the MozMEAO Jenkins service
* [x] Pause/disable the `MozMEAO MDN backup` pipeline within the MozMEAO Jenkins service
* [x] Delete the `migration-sync-user` from the MozIT AWS account
* [x] Delete the following unused S3 buckets from the MozIT AWS account and from the Terraform code in the Infra repo:
    * [x] `mdn-db-storage-anonymized-c2037ed87dd96008`
    * [x] `mdn-db-storage-c2037ed87dd96008`
    * [x] `mdn-db-storage-c2037ed87dd96008-logs`
    * [x] `mdn-downloads-c2037ed87dd96008`
    * [x] `mdn-downloads-c2037ed87dd96008-logs`

**Comment by escattone** [comment]
On Tuesday Oct. 30, I deleted the `mdn-downloads` S3 bucket in the MozMEAO account, and after about 2 hours, I was able to re-create it within the MozIT account. As an experiment, I also tried setting-up an S3 bucket with a custom domain name (`downloads.mdn.mozit.cloud`). I was able to do that, but the problem is that `https` can't be used with that bucket unless we add a CDN as well, since AWS does not allow custom certificates to be attached to S3 buckets. That's definitely not worth the cost given how infrequently the downloads bucket is currently used.

This is done.
