### ISSUE TITLE
Fix integration/acceptance test suite

### ISSUE THREAD

**Issue by escattone** [mdn/infra#155]
# User Story
As an MDN staff developer, I'd like a reliable integration/acceptance test suite that I can run before/after making a deployment to the stage environment to determine whether or not to continue to the production environment.

The current integration/acceptance test suite has become unreliable, mainly due to a subset of the Selenium-based tests.

# Acceptance Criteria
* [x] A reliable integration/acceptance test suite, i.e. one where failures indicate real issues (issues not related to the test code/framework itself). The test suite must run without failure 20 times out of 20 attempts.

# Tasks
* [x] Update `selenium` and related (e.g., `pytest-selenium`) Python packages
* [x] Fix or temporarily disable tests that intermittently fail

**Comment by escattone** [comment]
Current work in https://github.com/escattone/kuma/tree/upgrade-selenium-1462440

**Comment by escattone** [comment]
Good resource: https://github.com/SeleniumHQ/docker-selenium

**Comment by escattone** [comment]
Submitted https://github.com/mozilla/kuma/pull/5143 that represents the progress to date.

**Comment by escattone** [comment]
The combination of the following PR's may meet the acceptance criteria:
- https://github.com/mozilla/kuma/pull/5163
- https://github.com/mozilla/kuma/pull/5164
- https://github.com/mozilla/kuma/pull/5166

So far, 4/4 integration test suite runs against stage have succeeded.

**Comment by escattone** [comment]
🎉 The three PR's above did meet the acceptance criteria of 20/20 successful runs.

The integration test suite still contains tests that sometimes have to be re-run, for example these functional tests:
- `tests/functional/test_article_edit.py::test_edit_sign_in` (Chrome only, about 50% of the time)
- `tests/functional/test_article.py::test_header_signin` (Firefox only, about 4/21 runs)
- `tests/functional/test_dashboard.py::test_dashboard_load_page_two` (Chrome only, 1/21 runs)

as well as several in the headless test suite.
