### ISSUE TITLE
Upgrade Elasticsearch Server from 2.4 to 5.6

### ISSUE THREAD

**Issue by jwhitlock** [mdn/infra#8]
# User Story
As an MDN visitor, I want to use search after August 28, 2018, because I don't want to leave the site to use a better search engine.

# Acceptance Criteria
* Elasticsearch 5.6 used in staging, production, etc.

# Background
Elasticsearch 2.4 reaches end of life (EOL) on February 28, 2018, and since our Elastic Cloud service for MDN  is currently running 2.4, we will need to upgrade. However, the Elastic Cloud service will support version 2.4 for 6 months longer, until August 28, 2018.

* [bug 1464093](https://bugzilla.mozilla.org/show_bug.cgi?id=1464093) - More details
* https://github.com/mozmeao/infra/issues/666 - Original issue

This is from an email I received from Elastic:

> We highly recommend all customers to upgrade their 2.x clusters to Elasticsearch 5.6. Elasticsearch 5.6 has lots of goodness that will make your life a bit more zen and it is the perfect bridge to the new 6.0 release.
> 
> Usually, EOL means that we won’t provide support for clusters after this date. However, since this is the last version on the 2.x Elasticsearch branch, we understand that it can take time to test your application on a new major version, iron out any issues and complete the upgrade. We will therefore support Elasticsearch 2.4 clusters until August 28, 2018. If you have not upgraded your Elastic Cloud clusters by this date, Elasticsearch 2.4 will no longer be maintained and supported after this date.

Unlike the 0.x to 2.x update, 5.x requires that the client libraries are the same versions at the server.

# Tasks
- [x] Explore tasks to update to 5.x
- [x] Update ES queries to 2.x usage
- [x] Update ES client libraries to 2.x, update ES queries to 5.x
- [x] Update ES server, client libraries to 5.x in development environment
- [x] Create ES 5.x server in elastic.co
- [x] Ship ES 5.x to production, recreate indexes

**Comment by jwhitlock** [comment]
@escattone I'm thinking of splitting this story in two:

* The first part (which keeps this issue) would be the server update. My estimate would be 3 points, medium confidence
* The second part (new issue) would be the client update. My estimate would be 2 points, low confidence. It could be done in a separate sprint, or as a stretch task for this one.

Does that make sense?

**Comment by escattone** [comment]
@jwhitlock That makes sense to me as well, but you know much more than I do about this. On second thought, I don't think this should be in Sprint 1 of Q3.

**Comment by jwhitlock** [comment]
After some research, the ElasticSearch update will require simultaneous updates of the client library and the server to 5.x.  The 5.x server doesn't accept 2.x queries and document mappings.  The update process is a bit more complex, and we'll lose site search for about an hour, but I think we can still do it in this sprint.

**Comment by jwhitlock** [comment]
ElasticSearch 5.4.10 is in use in development, staging, and production. We used new 5.x servers in elastic.co, so we decommissioned the now unused 2.4 servers. Thanks to @escattone and @safwanrahman for helping with this project.
