### ISSUE TITLE
Ensure "standby-push" branch works for the kuma and kumascript pipelines on new CI/CD service.

### ISSUE THREAD

**Issue by escattone** [mdn/infra#88]
# User story
As an MDN developer, I want to ensure our CI/CD code for the "standby-push" branch of the `kuma` and `kumascript` pipelines works within IT's CI/CD infrastructure so that we can deploy code to the new standby cluster.

# Acceptance criteria
* The Kuma `Jenkinsfile` runs successfully (runs tests and deploys code to the new `germany` cluster) for the `standby-push` branch
* The Kumascript `Jenkinsfile` runs successfully (runs tests and deploys code to the new `germany` cluster) for the `standby-push` branch

# Tasks
- [x] Configure Jenkins with Kubernetes credentials for the new standby cluster in `germany` (@limed, @escattone)
- [x] Modify the [Groovy utils in Kuma](https://github.com/mozilla/kuma/blob/master/Jenkinsfiles/utils.groovy) such that `get_region()` returns `germany` instead of `frankfurt` for the IT-owned Jenkins pipeline (@escattone)
- [x] Test both the Kuma and Kumascript `Jenkinsfile` (as detailed in the acceptance criteria) (@escattone)

**Comment by escattone** [comment]
This issue depends on https://github.com/mdn/infra/issues/78.

**Comment by escattone** [comment]
Confirmed fully successful `kuma` and `kumascript` pushes on Oct. 11, 2018.

<img width="1005" alt="screen shot 2018-10-11 at 2 52 41 pm" src="https://user-images.githubusercontent.com/3743693/46836196-63874300-cd65-11e8-89a3-5d934883292b.png">

<img width="1083" alt="screen shot 2018-10-11 at 2 53 39 pm" src="https://user-images.githubusercontent.com/3743693/46836230-844f9880-cd65-11e8-9b89-3a743c50be7d.png">
