### ISSUE TITLE
Automate Daily RDS Backups

### ISSUE THREAD

**Issue by escattone** [mdn/infra#89]
# User story
As an MDN developer, I want to ensure we backup the production database on a regular basis via an automated process.

# Acceptance Criteria
* [x] Backups of the production database are automated to be made daily
* [x] First of the backups has completed successfully
* [x] Backup successfully decrypted

# Tasks:
* [x] Create and register a new `mdn-rds-backup` Docker image on DockerHub (`mdnwebdocs`)
* [x] Create or ensure that an S3 bucket for RDS backups has been created and is defined in the Terraform
* [x] Create an AWS IAM user for syncing from the K8s CronJob to the S3 bucket
* [x] Create and deploy secrets for running the RDS backups
* [x] Create a K8s CronJob from the current RDS backup tool
* [x] Deploy the K8s CronJob
* [x] Decrypt a backup file

**Comment by escattone** [comment]
The first run completed flawlessly:
```
rjohnson-25186:k8s rjohnson$ kc get pods -a
NAME                                READY     STATUS      RESTARTS   AGE
api-7dd4b596f9-xr7jm                1/1       Running     1          21h
celery-worker-7d5bc4d77c-26bjt      1/1       Running     0          21h
kumascript-676f4c54fb-vv2wx         1/1       Running     0          21h
mdn-efs-setup-62wqk                 0/1       Completed   0          1d
mdn-rds-backup-1538611200-sdj55     0/1       Completed   0          16h
mdn-restore-prod-1538661600-84r86   0/1       Completed   0          2h
mdn-restore-prod-1538665200-b9gth   0/1       Completed   0          1h
mdn-restore-prod-1538668800-5jcz8   0/1       Completed   0          9m
web-84965df79b-4fk6w                1/1       Running     0          21h
rjohnson-25186:k8s rjohnson$ kc logs mdn-rds-backup-1538611200-sdj55
developer_mozilla_org backup started at Thu Oct  4 00:00:34 UTC 2018
Encrypted backup output file: /backup/developer_mozilla_org/developer_mozilla_org.2018-10-04.sql.gz.aes
Starting MySQL backup on Thu Oct  4 00:00:34 UTC 2018
Finished MySQL backup on Thu Oct  4 00:25:11 UTC 2018
Pushing /backup/developer_mozilla_org/developer_mozilla_org.2018-10-04.sql.gz.aes to s3://mdn-backup-bucket-0899eecc1f038f41/backups/developer_mozilla_org/
upload: ./developer_mozilla_org.2018-10-04.sql.gz.aes to s3://mdn-backup-bucket-0899eecc1f038f41/backups/developer_mozilla_org/developer_mozilla_org.2018-10-04.sql.gz.aes
Finished pushing to S3
updating Deadmanssnitch: https://nosnch.in/0bd44c1fbb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    16  100    16    0     0     42      0 --:--:-- --:--:-- --:--:--    42
Got it, thanks!
Deadmanssnitch updated
developer_mozilla_org backup finished at Thu Oct  4 00:26:35 UTC 2018
rjohnson-25186:k8s rjohnson$ kc get cronjobs
NAME               SCHEDULE   SUSPEND   ACTIVE    LAST SCHEDULE   AGE
mdn-rds-backup     @daily     False     0         Wed, 03 Oct 2018 17:00:00 -0700
mdn-restore-prod   @hourly    False     0         Thu, 04 Oct 2018 09:00:00 -0700
```
<img width="1110" alt="screen shot 2018-10-04 at 9 26 39 am" src="https://user-images.githubusercontent.com/3743693/46488493-ab332b00-c7b7-11e8-8c55-35f7e9929507.png">

**Comment by escattone** [comment]
@metadave and @jgmize and I decided that we'd like the RDS backups to be performed daily rather than weekly, to reduce the risk of data loss. Just a reminder, the RDS backup is performed on the read replica of the production database, not the production DB itself, so there is no performance penalty.

**Comment by escattone** [comment]
I re-opened this since @metadave reminded me that we should test that we can decrypt the backup, so I've added that as another task.

**Comment by escattone** [comment]
I did several things related to testing that the backup could be decrypted:
- added read access to the `mdn-shared-backup-c2037ed87dd96008` and `mdn-backup-bucket-0899eecc1f038f41` S3 buckets for all of the nodes in the `oregon` and `germany` clusters via the IAM roles associated with the nodes (this is a permanent change)
- started an admin node within the standby cluster using `make k8s-admin-node`
- ran the following on the admin node:
```sh
aws s3 cp s3://mdn-backup-bucket-0899eecc1f038f41/backups/developer_mozilla_org/developer_mozilla_org.2018-10-05.sql.gz.aes .
openssl aes-256-cbc -d -in developer_mozilla_org.2018-10-05.sql.gz.aes -pass pass:XXX | zcat | head
```
Decryption successful! ✅
