### ISSUE TITLE
Update Primary Stage/Prod CDN's to Support Contribution Feature

### ISSUE THREAD

**Issue by escattone** [mdn/infra#91]
# User story
As an MDN developer, I want to ensure that the primary stage and production CDN's support the new contribution feature.

# Acceptance Criteria
* [x] New `dwf_contrib_beta` cookie remains unchanged when switching among the landing page and/or the document pages on stage (developer.allizom.org)
* [x] New `dwf_contrib_beta` cookie remains unchanged when switching among the landing page and/or the document pages on prod (developer.mozilla.org)

# Tasks:
* [x] New `dwf_contrib_beta` cookie is added to the cookie whitelist on all appropriate behaviors on the primary stage CDN as well as the Terraform
* [x] New `dwf_contrib_beta` cookie is added to the cookie whitelist on all appropriate behaviors on the primary prod CDN as well as the Terraform
